import GetGuest from '../components/GetGuest'
import Layout from 'components/Layout'
import ArrivalConfirmation from 'components/ArrivalConfirmation'
import useGuest from 'lib/getGuest'

const MyApp = ({
}) => {
  const { data, isLoading } = useGuest()

  if (isLoading) <>Loading</>

  return (
    <Layout>
      <GetGuest />
      <h3>Tes dashboard wedding apps</h3>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <p>Halo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding appsHalo wedding apps</p>
      <ArrivalConfirmation time={data?.[0]?.time} />
    </Layout >
  )

}

export default MyApp

